name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      - name: Install dependencies
        run: npm install

      # Build your Vue.js project
      - name: Build
        run: npm run build

      # Start your Vue.js application
      - name: Start App
        run: npm start

      # Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.5.1
